export const generateMockSummary = (audioBlob) => {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve({
        title: "Mock Recording " + new Date().toLocaleTimeString(),
        summary: "This is a mock summary for the recording. In a real application, this would be generated by processing the audio content.",
      });
    }, 1000); // Simulate a 1-second delay
  });
};